Feature: demo to pull data from json files
  Background: cfg base url and load data from feature files
  Given url apiUrl
    And path '/getAllEmployees'
    When method Get
    Then status 200
    And def noOfEmpsBeforeSaving = response.length
  And path '/login'
    #here to login we will get the json from this json file instead of hard coding here
  * def credentials = read('classpath:bdds/json/credentials.json')
    * def payload  = read ('classpath:bdds/json/employee.json')

      # since the same json will be loaded from file everytime we run the test case, here we can override with dynamic values

      # load the java class
    * def empFakerClass = Java.type('helpers.EmpFaker')
    # create obj for this class to call instance methods
  * def empObj = new empFakerClass()

      # modify the payload with the random value generated by java method
  * set payload.empname = empObj.getEmployeeName()

  And request credentials
  When method post
  Then status 200
  And def token = response.token
    * print token
    * print 'size earlier was'+ noOfEmpsBeforeSaving

  Scenario: read json data from file & call java methods to modify it

  Given path  '/saveEmp'
    * set payload.empno = noOfEmpsBeforeSaving +1
    And header Authorization = token
    And request payload
    When method post
    Then status 200
    # assert the response with payload data with what we sent
    * print 'size after savings is ' +noOfEmpsBeforeSaving
    * def nv = noOfEmpsBeforeSaving
    * print 'var nv value is '+nv
    And match response[13].empname == payload.empname